---
# handlers file for node
- name: Write bootstrapped fact
  ansible.builtin.lineinfile:
    line: "bootstrapped=true"
    path: /etc/ansible/facts.d/kubernetes.fact
  become: true

- name: Update node role
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ item }}"
        labels:
          node-role.kubernetes.io/worker: worker
  delegate_to: "{{ bootstrap_node }}"
  become: false